(function(){
  function id(name){return document.getElementById(name);}
  var startScreen=id('startScreen'),quizScreen=id('quizScreen'),summaryScreen=id('summaryScreen');
  if(!startScreen||!quizScreen||!summaryScreen)return;
  var nextBtn=id('nextBtn'),submitBtn=id('submitBtn'),answerForm=id('answerForm'),answerInput=id('answerInput'),feedbackBox=id('feedbackBox'),feedbackTitle=id('feedbackTitle'),correctWord=id('correctWord'),enDefs=id('enDefs'),enEx=id('enEx'),zhDef=id('zhDef'),scoreText=id('scoreText'),scoreNote=id('scoreNote'),summaryTableBody=id('summaryTableBody'),homeBtn=id('homeBtn');
  startScreen.innerHTML='<h2>Choose a Week</h2><p class="subtitle">Tap a week to start. Core Words and Challenge Words will be mixed in a random order.</p><div id="weekGrid" class="week-grid"></div><details class="settings-card no-print"><summary>Parent Voice Settings</summary><div class="settings-panel"><p class="tiny-note">Test voices here and choose the one that sounds best on this device. The choice is saved in this browser only.</p><div class="form-row"><label for="voiceSelect">English Voice</label><select id="voiceSelect"><option value="">Auto-select best voice</option></select></div><div class="range-row"><label for="wordRate">Word Speed: <span id="wordRateValue" class="rate-value">0.80</span></label><input id="wordRate" type="range" min="0.60" max="1.05" step="0.05" value="0.80"></div><div class="range-row"><label for="sentenceRate">Meaning / Example Speed: <span id="sentenceRateValue" class="rate-value">0.82</span></label><input id="sentenceRate" type="range" min="0.65" max="1.10" step="0.05" value="0.82"></div><div class="button-row"><button id="testVoiceBtn" type="button" class="secondary">Test Voice</button><button id="resetVoiceBtn" type="button" class="secondary">Reset Voice Settings</button></div></div></details>';
  var weekGrid=id('weekGrid');
  Object.keys(vocabularyData).forEach(function(k){var b=document.createElement('button');b.type='button';b.className='week-btn';b.innerHTML='<span>'+formatWeekLabel(k)+'</span><small>'+weekMeta[k]+'</small>';b.addEventListener('click',function(){startQuizEnhanced(k)});weekGrid.appendChild(b)});
  nextBtn.insertAdjacentHTML('beforebegin','<button id="skipReadBtn" type="button" class="secondary" style="display:none">Skip Reading</button>');
  var skipReadBtn=id('skipReadBtn');correctWord.insertAdjacentHTML('afterend','<p id="readingStatus" class="reading-status" style="display:none">Reading the meaning and example...</p>');var readingStatus=id('readingStatus');
  var scoreCard=scoreText.parentElement;scoreCard.insertAdjacentHTML('beforeend','<p class="summary-meta" id="resultDate"></p><p class="summary-meta" id="mistakeCount"></p>');var resultDate=id('resultDate'),mistakeCount=id('mistakeCount');
  var tableWrap=summaryTableBody.closest('.table-wrap');tableWrap.insertAdjacentHTML('beforebegin','<p class="print-note">You can save the current view by taking a screenshot, or use Print / Save as PDF.</p><div class="button-row no-print summary-controls"><button id="showAllBtn" type="button" class="filter-btn active">Show All Words</button><button id="showMistakesBtn" type="button" class="filter-btn">Show Mistakes Only</button></div><p class="summary-meta" id="summaryModeText"></p><div id="emptyMistakes" class="empty-state" style="display:none">No mistakes. Perfect work!</div>');
  var showAllBtn=id('showAllBtn'),showMistakesBtn=id('showMistakesBtn'),summaryModeText=id('summaryModeText'),emptyMistakes=id('emptyMistakes');homeBtn.insertAdjacentHTML('beforebegin','<button id="printBtn" type="button">Print / Save as PDF</button>');var printBtn=id('printBtn');homeBtn.parentElement.classList.add('no-print');
  var KEY='lifeScienceQuizVoicePrefs';function getPrefs(){var d={voiceKey:'',wordRate:.8,sentenceRate:.82};try{return Object.assign(d,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return d}}function savePrefs(p){try{localStorage.setItem(KEY,JSON.stringify(p))}catch(e){}}function voiceKey(v){return v.name+'||'+v.lang}function englishVoices(){if(!speechSynthesis)return[];return speechSynthesis.getVoices().filter(function(v){return v.lang&&v.lang.toLowerCase().indexOf('en')===0}).sort(function(a,b){return(a.lang+a.name).localeCompare(b.lang+b.name)})}
  var voiceSelect=id('voiceSelect'),wordRate=id('wordRate'),wordRateValue=id('wordRateValue'),sentenceRate=id('sentenceRate'),sentenceRateValue=id('sentenceRateValue'),testVoiceBtn=id('testVoiceBtn'),resetVoiceBtn=id('resetVoiceBtn');
  function populateVoices(){var p=getPrefs();voiceSelect.innerHTML='<option value="">Auto-select best voice</option>';englishVoices().forEach(function(v){var o=document.createElement('option');o.value=voiceKey(v);o.textContent=v.name+' — '+v.lang;voiceSelect.appendChild(o)});voiceSelect.value=p.voiceKey||''}
  function bestVoiceEnhanced(){var voices=speechSynthesis.getVoices(),p=getPrefs();if(p.voiceKey){var s=voices.find(function(v){return voiceKey(v)===p.voiceKey});if(s)return s}var names=['Google US English','Microsoft Aria','Microsoft Jenny','Microsoft Ava','Microsoft Guy','Samantha','Karen','Daniel','Serena'];for(var i=0;i<names.length;i++){var t=names[i].toLowerCase(),f=voices.find(function(v){return v.name.toLowerCase().indexOf(t)>=0&&v.lang.toLowerCase().indexOf('en')>=0});if(f)return f}return voices.find(function(v){return v.name.toLowerCase().indexOf('natural')>=0&&v.lang.toLowerCase().indexOf('en-')>=0})||voices.find(function(v){return v.name.toLowerCase().indexOf('google')>=0&&v.lang.toLowerCase().indexOf('en-us')>=0})||voices.find(function(v){return v.lang==='en-US'||v.lang==='en-GB'})||voices.find(function(v){return v.lang&&v.lang.toLowerCase().indexOf('en')===0})||null}
  function speakTextEnhanced(text,opt){opt=opt||{};if(!speechSynthesis||!SpeechSynthesisUtterance){if(opt.onend)opt.onend();return}speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.rate=opt.rate||.84;u.pitch=1;u.volume=1;var v=bestVoiceEnhanced();if(v){u.voice=v;u.lang=v.lang||'en-US'}else u.lang='en-US';var done=false;u.onend=function(){if(done)return;done=true;if(opt.onend)opt.onend()};u.onerror=u.onend;speechSynthesis.speak(u)}
  function setupVoice(){var p=getPrefs();wordRate.value=p.wordRate;wordRateValue.textContent=Number(p.wordRate).toFixed(2);sentenceRate.value=p.sentenceRate;sentenceRateValue.textContent=Number(p.sentenceRate).toFixed(2);populateVoices();voiceSelect.addEventListener('change',function(){var p=getPrefs();p.voiceKey=voiceSelect.value;savePrefs(p)});wordRate.addEventListener('input',function(){var p=getPrefs();p.wordRate=Number(wordRate.value);wordRateValue.textContent=p.wordRate.toFixed(2);savePrefs(p)});sentenceRate.addEventListener('input',function(){var p=getPrefs();p.sentenceRate=Number(sentenceRate.value);sentenceRateValue.textContent=p.sentenceRate.toFixed(2);savePrefs(p)});testVoiceBtn.addEventListener('click',function(){var p=getPrefs();speakTextEnhanced('The word is photosynthesis. Photosynthesis means: the process plants use to make food from light, water, and carbon dioxide. Example: Photosynthesis happens mostly in green leaves.',{rate:p.sentenceRate})});resetVoiceBtn.addEventListener('click',function(){try{localStorage.removeItem(KEY)}catch(e){}setupVoice()})}setupVoice();if(window.speechSynthesis)window.speechSynthesis.onvoiceschanged=populateVoices;
  speak=function(word){speakTextEnhanced(word,{rate:getPrefs().wordRate})};function finishReading(){readingStatus.style.display='none';skipReadBtn.style.display='none';nextBtn.disabled=false;nextBtn.focus()}function readAfterAnswer(item){readingStatus.style.display='block';skipReadBtn.style.display='inline-flex';nextBtn.disabled=true;var meaning=item.en_defs&&item.en_defs.length?item.en_defs[0]:'';speakTextEnhanced('The word is '+item.word+'. '+item.word+' means: '+meaning+'. Example: '+item.en_ex,{rate:getPrefs().sentenceRate,onend:finishReading})}skipReadBtn.addEventListener('click',function(){if(speechSynthesis)speechSynthesis.cancel();finishReading()});
  function startQuizEnhanced(k){selectedWeekKey=k;currentWords=shuffle(vocabularyData[selectedWeekKey]||[]);currentIndex=0;score=0;results=[];if(!currentWords.length){alert('No words found for this week.');return}show(quizScreen);renderWord()}
  var oldReset=resetAnswer;resetAnswer=function(){oldReset();skipReadBtn.style.display='none';readingStatus.style.display='none';nextBtn.disabled=true};
  answerForm.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();if(answerInput.disabled)return;var item=currentWords[currentIndex],userAnswer=answerInput.value.trim(),isCorrect=normalize(userAnswer)===normalize(item.word);if(isCorrect)score+=1;results.push({word:item.word,category:item.category,userAnswer:userAnswer,isCorrect:isCorrect});answerInput.disabled=true;submitBtn.disabled=true;nextBtn.style.display='inline-flex';nextBtn.disabled=true;feedbackBox.className='feedback visible '+(isCorrect?'correct':'wrong');feedbackTitle.textContent=isCorrect?'Correct!':'Try Again Next Time';correctWord.textContent=item.category+' Word — Correct spelling: '+item.word;addDefs(enDefs,item.en_defs);enEx.textContent=item.en_ex;zhDef.textContent=item.zh_def;readAfterAnswer(item)},true);
  var summaryFilter='all';function visibleResults(){return summaryFilter==='mistakes'?results.filter(function(r){return !r.isCorrect}):results}function updateFilterButtons(){showAllBtn.classList.toggle('active',summaryFilter==='all');showMistakesBtn.classList.toggle('active',summaryFilter==='mistakes')}function renderSummaryTableEnhanced(){var mistakes=results.filter(function(r){return !r.isCorrect}).length;summaryModeText.textContent=summaryFilter==='mistakes'?'Showing: Mistakes Only ('+mistakes+')':'Showing: All Words ('+results.length+')';emptyMistakes.style.display=(summaryFilter==='mistakes'&&mistakes===0)?'block':'none';summaryTableBody.innerHTML='';visibleResults().forEach(function(r){var row=document.createElement('tr');if(!r.isCorrect)row.classList.add('wrong-row');var w=document.createElement('td');w.textContent=r.word;var c=document.createElement('td');var b=document.createElement('span');b.className='badge';b.textContent=r.category;c.appendChild(b);var a=document.createElement('td');a.textContent=r.userAnswer||'No answer';if(!r.isCorrect)a.classList.add('wrong-answer');var res=document.createElement('td');res.className='result';res.textContent=r.isCorrect?'✔️':'❌';row.append(w,c,a,res);summaryTableBody.appendChild(row)})}function setSummaryFilter(mode){summaryFilter=mode;updateFilterButtons();renderSummaryTableEnhanced()}renderSummary=function(){var total=currentWords.length,percent=total?Math.round(score/total*100):0,mistakes=results.filter(function(r){return !r.isCorrect}).length,now=new Date();scoreText.textContent='Score: '+score+' / '+total+' ('+percent+'%)';scoreNote.textContent=percent===100?'Perfect work!':percent>=80?'Great job!':percent>=60?'Good practice. Keep going!':'Keep practicing. You can improve!';resultDate.textContent='Completed: '+now.toLocaleString('en-US',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});mistakeCount.textContent='Mistakes: '+mistakes+' / '+total;summaryFilter='all';updateFilterButtons();renderSummaryTableEnhanced()};showAllBtn.addEventListener('click',function(){setSummaryFilter('all')});showMistakesBtn.addEventListener('click',function(){setSummaryFilter('mistakes')});printBtn.addEventListener('click',function(){window.print()});
})();